import { writable } from 'svelte/store';
export let rentalDataSvelteStore = writable([
  {
    'Listing No': 1,
    'Stratified Area': 'Alliston/Bradford',
    'Municipality': 'Barrie',
    'Street #': 280,
    'Street Name': '1',
    'Housing Type': 'House',
    'UnitSize': '2 Bedrooms	',
    'Secondary Suite': 'true',
    'Monthly Rent': '1300',
    'Utilities Included': 'true',
    'Landlord Type': 'private',
    'Stability': '1 year',
  },
  {
    ListingNo: 2,
    StratifiedArea: 'Alliston/Bradford',
    'Municipality': 'Bradford West',
    'Street #': '1',
    'Street Name': '1',
    'Housing Type': '1',
    'UnitSize': '2',
    'Secondary Suite': '2',
    'Monthly Rent': '3',
    'Utilities Included': '3',
    'Landlord Type': '3',
    'Stability': '2',
  },
  {
    ListingNo: 3,
    StratifiedArea: 'Alliston/Bradford',
    'Municipality': 'Bradford West',
    'Street #': '1',
    'Street Name': '1',
    'Housing Type': '1',
    'UnitSize': '2',
    'Secondary Suite': '2',
    'Monthly Rent': '3',
    'Utilities Included': '3',
    'Landlord Type': '3',
    'Stability': '2',
  },
  {
    ListingNo: 4,
    StratifiedArea: 'Alliston/Bradford',
    'Municipality': 'Bradford West',
    'Street #': '1',
    'Street Name': '1',
    'Housing Type': '1',
    'UnitSize': '2',
    'Secondary Suite': '2',
    'Monthly Rent': '3',
    'Utilities Included': '3',
    'Landlord Type': '3',
    'Stability': '2',
  },
  {
    ListingNo: 5,
    StratifiedArea: 'Alliston/Bradford',
    'Municipality': 'Bradford West',
    'Street #': '1',
    'Street Name': '1',
    'Housing Type': '1',
    'UnitSize': '2',
    'Secondary Suite': '2',
    'Monthly Rent': '3',
    'Utilities Included': '3',
    'Landlord Type': '3',
    'Stability': '2',
  },
  {
    ListingNo: 6,
    StratifiedArea: 'Alliston/Bradford',
    'Municipality': 'Bradford West',
    'Street #': '1',
    'Street Name': '1',
    'Housing Type': '1',
    'UnitSize': '2',
    'Secondary Suite': '2',
    'Monthly Rent': '3',
    'Utilities Included': '3',
    'Landlord Type': '3',
    'Stability': '2',
  },
]);
